spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ## Inventory Service Route
        - id : inventory-service
          uri : lb://inventory-service
          predicates:
          - Path=/api/v1/inventory/**
        ## Notification Service Route
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
        ## Order Service Route
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order
        ## Product Service Route
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        ## Eureka Service Route
        - id: eureka-service
          uri: http://localhost:8761/
          predicates:
            - Path=/eureka/**
server:
  port: 8084
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true