spring:
  application:
    name: ORDER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
